name: inshop
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  provider: ^6.1.2
  supabase_flutter: ^2.0.0
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  supabase_flutter: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
